Repository fluxcd/website, pull requests merged in 2021-07, with the labels that each got.

#381 remove 1px green border from flat buttons
  assets/scss/_buttons.scss
  assets/scss/blocks/_hero.scss
Labels: landing page, pretty

#371 disable foldable menu for now
  config.toml
Labels: pretty

#391 Fix two broken links in legacy docs
  content/en/legacy/flux/faq.md
  content/en/legacy/flux/get-started.md
Labels: documentation

#385 add flux facts to main page
  assets/scss/blocks/_hero.scss
  content/en/_index.html
Labels: landing page

#423 Fix error in webhook receiver guide
  content/en/docs/guides/webhook-receivers.md
Labels: documentation

#428 Remove 'needs-name' logic - we ended up not using it.
  adopters/1-flux-v2.yaml
  adopters/2-flagger.yaml
  adopters/3-flux-v1.yaml
  adopters/README.md
  hack/adopters.py
Labels: landing page, meta

#429 Fix a number of python lint issues
  hack/adopters.py
  hack/contributors.py
  hack/gen-content.py
Labels: meta

#435 Add August blog post
  content/en/blog/2021-08-02-august-update.md
  static/img/2021-07-flux-users-screenshot.png
  static/img/2021-07-tabs-screenshot.png
Labels: blog

#313 Update HelmRelease creation example
  content/en/docs/use-cases/helm.md
Labels: documentation
