Repository fluxcd/website, pull requests merged in 2021-08, with the labels that each got.

#441 Fix install patch path
  content/en/docs/installation.md
Labels: bug, documentation

#454 Add Nix install instruction
  content/en/docs/installation.md
Labels: blocked-dco

#469 Docs improvements
  content/en/docs/get-started.md
  content/en/docs/installation.md
Labels: documentation

#442 Update helm.md - 2
  content/en/docs/use-cases/helm.md
Labels: documentation

#478 Update GA roadmap
  content/en/roadmap.md
Labels: area/roadmap

#490 add September blog post
  content/en/blog/2021-08-30-september-update.md
  static/img/2021-08-flux-operator-screenshot1.png
  static/img/2021-08-flux-operator-screenshot2.png
  static/img/2021-08-resources-section.png
  static/img/2021-08-somtochi-avatar.jpg
Labels: area/blog
