Repository fluxcd/website, pull requests merged in 2021-05, with the labels that each got.

#260 Update namespace of kubectl command
  content/en/docs/guides/monitoring.md
Labels: blocked-dco

#268 Removed duplicate word
  content/en/docs/guides/notifications.md
Labels: blocked-dco

#278 Rephrase landing somewhat
  config.toml
  content/en/_index.html
Labels: landing page

#283 Fix helm remediation options naming
  content/en/docs/migration/helm-operator-migration.md
  content/en/docs/use-cases/helm.md
Labels: documentation

#292 Move happn to Flux2 adopters
  adopters/1-flux-v2.yaml
  adopters/3-flux-v1.yaml
  adopters/logos/happn.png
Labels: blocked-dco

#298 Add FAQ item for Helm 'entity too large' error
  content/en/docs/contributing/.gitignore
  content/en/docs/faq/_index.md
Labels: documentation

#299 Ways of structuring your repositories
  content/en/docs/guides/repository-structure.md
Labels: documentation

#303 Improve adopters page preview
  hack/generate-adopters-pages.py
Labels: pretty

#304 Add GoFish, yay and SSH passphrase to install docs
  content/en/docs/installation/_index.md
Labels: documentation
