Repository fluxcd/website, pull requests merged in 2021-06, with the labels that each got.

#311 Update image-update.md to allow secret creation
  content/en/docs/guides/image-update.md
Labels: documentation

#326 Update docs to Kustomize v4
  content/en/docs/faq/_index.md
Labels: documentation

#328 Set `HUGO_ENV` for production build
  netlify.toml
Labels: bug

#329 Netlify fixes
  Makefile
  netlify.toml
Labels: bug

#338 Update source-watcher documentation
  content/en/docs/gitops-toolkit/source-watcher.md
Labels: documentation

#350 Add contributors section
  .github/workflows/update-contributors.yaml
  .gitignore
  content/en/.gitignore
  content/en/_index.html
  content/en/contributors_include.html
  hack/contributors.py
  layouts/shortcodes/blocks/contributors.html
  requirements.txt
Labels: enhancement, landing page
