Repository fluxcd/website, pull requests merged in 2023-05, with the labels that each got.

#1447 April 2023 Update
  content/en/blog/2023-05-02-april-update/crew-featured.jpg
  content/en/blog/2023-05-02-april-update/flickr/52836983222_6ce2d944d1_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52837250597_4e58850828_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52837568501_2e02d0e008_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52837739714_16f4236737_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52837980005_f47668d2a3_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52837980010_efbd49ee6c_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52838007744_4757357c6a_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52838225580_011a31f6f5_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52838267018_5424206e7a_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52838267043_e34b229b67_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52838267158_fd0dab7a29_c.jpg
  content/en/blog/2023-05-02-april-update/flickr/52838969604_6f1b6a1968_c.jpg
  content/en/blog/2023-05-02-april-update/index.md
  content/en/blog/2023-05-02-april-update/our-pics/20230418_155249.jpg
  content/en/blog/2023-05-02-april-update/our-pics/20230421_154118.jpg
  content/en/blog/2023-05-02-april-update/our-pics/20230421_155347.jpg
  content/en/blog/2023-05-02-april-update/our-pics/image (1).jpeg
  content/en/blog/2023-05-02-april-update/our-pics/image (2).jpeg
  content/en/blog/2023-05-02-april-update/our-pics/image.jpeg
  content/en/blog/2023-05-02-april-update/our-pics/image_4.jpeg
  content/en/blog/2023-05-02-april-update/our-pics/image_5.jpeg
  data/resources.yaml
  templates/monthly-update.md
Labels: area/blog

#1489 minor corrections in get-started.md file
  content/en/flux/get-started.md
Labels: area/docs

#1490 fix spelling mistake
  content/en/flux/cmd/_index.md
  content/en/flux/installation.md
Labels: area/docs

#1492 Add Nuvme to adopters
  data/adopters/1-flux-v2.yaml
  static/img/logos/nuvme.png
Labels: area/adopters

#1498 flagger: Update linkerd installation docs
  content/en/flagger/tutorials/linkerd-progressive-delivery.md
Labels: area/docs, area/flagger

#1499 Add Workload Identity to Azure guide
  content/en/flux/use-cases/azure.md
Labels: area/docs

#1500 Update verify instructions to cosign v2
  content/en/flux/security/_index.md
Labels: area/docs, area/security

#1501 Correct gcp image automation link in gcp source repo use-case
  content/en/flux/use-cases/gcp-source-repository.md
Labels: area/docs

#1507 Update GitHub Actions examples syntax + actions versions
  content/en/flux/guides/sortable-image-tags.md
  content/en/flux/use-cases/gh-actions-app-builder.md
  content/en/flux/use-cases/gh-actions-auto-pr.md
  content/en/flux/use-cases/gh-actions-helm-promotion.md
  content/en/flux/use-cases/gh-actions-manifest-generation.md
Labels: area/docs

#1503 Update docs to Flux RC.4
  content/en/flux/cmd/_index.md
  content/en/flux/components/kustomize/_index.md
  content/en/flux/faq.md
  content/en/flux/gitops-toolkit/packages.md
  content/en/flux/guides/cron-job-image-auth.md
  content/en/flux/guides/helmreleases.md
  content/en/flux/guides/image-update.md
  content/en/flux/guides/mozilla-sops.md
  content/en/flux/guides/sealed-secrets.md
  content/en/flux/installation.md
  content/en/roadmap.md
Labels: area/docs
