Repository fluxcd/website, pull requests merged in 2023-12, with the labels that each got.

#1726 Add supported versions and release cadence link to roadmap
  content/en/roadmap.md
Labels: backport:v2-0

#1732 Update Helm GA tasks
  content/en/roadmap.md
Labels: area/roadmap

#1745 Update v2-1 branch from main
  package-lock.json
  package.json
Labels: hold

#1740 Prepare release of Flux 2.2 - v2.1 archive
  hugo.yaml
Labels: hold

#1741 Prepare release Flux 2.2 - main branch
  hugo.yaml
Labels: hold

#1718 Update HelmRelease, Alerts and Providers to Flux v2.2.0
  content/en/flagger/install/flagger-install-with-flux.md
  content/en/flux/cheatsheets/oci-artifacts.md
  content/en/flux/cheatsheets/troubleshooting.md
  content/en/flux/faq.md
  content/en/flux/flux-e2e.md
  content/en/flux/gitops-toolkit/packages.md
  content/en/flux/guides/helmreleases.md
  content/en/flux/guides/image-update.md
  content/en/flux/guides/repository-structure.md
  content/en/flux/guides/sealed-secrets.md
  content/en/flux/installation/configuration/sharding.md
  content/en/flux/migration/helm-operator-migration.md
  content/en/flux/monitoring/alerts.md
  content/en/flux/monitoring/custom-metrics.md
  content/en/flux/use-cases/gh-actions-helm-promotion.md
  content/en/flux/use-cases/helm.md
  content/en/flux/use-cases/karmada.md
Labels: area/docs

#1731 Update kustomize-controller options
  content/en/flux/components/kustomize/options.md
Labels: area/docs, area/flux

#1739 Update HelmRelease documentation
  content/en/flux/components/helm/options.md
  content/en/flux/guides/helmreleases.md
  content/en/flux/installation/_index.md
  content/en/flux/installation/configuration/helm-drift-detection.md
  content/en/flux/installation/configuration/helm-oom-detection.md
  content/en/flux/security/best-practices.md
  content/en/flux/use-cases/gh-actions-helm-promotion.md
Labels: area/docs

#1744 Flux v2.2.0 release blog
  content/en/blog/2023-12-12-announcing-flux-v2.2.0/index.md
Labels: area/blog

#1751 update hugo to v0.121.1
  netlify.toml
Labels: backport:v2-0, backport:v2-1

#1754 Polish Gitea PAT permission statements
  content/en/flux/installation/bootstrap/gitea.md
Labels: area/docs, area/flux

#1755 Add Kubernetes 1.29 to supported versions
  content/en/flux/installation/_index.md
Labels: area/docs, area/flux

#1757 fix: typo
  content/en/flux/installation/upgrade.md
Labels: backport:v2-2
