Repository fluxcd/website, pull requests merged in 2023-02, with the labels that each got.

#1333 Prepare next monthly update
  content/en/blog/2023-02-01-january-update.md
  content/en/flux/_index.md
  hack/new-update-post.py
  templates/monthly-update.md
Labels: area/blog

#1367 Add SBOM, SLSA and CVE scanning to the security doc
  content/en/flux/security/_index.md
Labels: area/docs, area/security

#1354 Document CacheSecretsAndConfigMaps feature flag in source-controller
  content/en/flux/components/helm/options.md
  content/en/flux/components/source/options.md
Labels: area/docs

#1368 Add CacheSecretsAndConfigMaps feature gate to all controllers
  content/en/flux/components/helm/options.md
  content/en/flux/components/image/options.md
  content/en/flux/components/kustomize/options.md
  content/en/flux/components/notification/options.md
  content/en/flux/components/source/options.md
Labels: area/docs

#1371 Add guest post on combining Flux and Pulumi
  content/en/blog/2023-02-14-flux-pulumi-superpowers/flying-sparkles-purple-cape-featured.png
  content/en/blog/2023-02-14-flux-pulumi-superpowers/index.md
Labels: area/blog

#1377 fix left float
  content/en/blog/2023-02-14-flux-pulumi-superpowers/index.md
Labels: ux

#1379 Update gallery theme, make docsy updates manual
  .github/dependabot.yml
  go.mod
  go.sum
Labels: dependencies

#1381 Add Wildlife Studios to adopters
  data/adopters/1-flux-v2.yaml
  data/adopters/2-flagger.yaml
  static/img/logos/wildlifestudios.png
Labels: area/adopters

#1382 Update Weave GitOps links
  content/en/blog/2022-04-04-march-update/index.md
  content/en/blog/2022-08-02-july-update/index.md
  content/en/blog/2022-10-04-september-update/index.md
  content/en/blog/2022-12-01-november-update/index.md
  content/en/ecosystem/index.md
Labels: area/docs

#1373 Remove image reflector deprecated options
  content/en/flux/components/image/options.md
Labels: area/docs

#1383 security: Add view, edit and admin roles to RBAC docs
  content/en/flux/security/_index.md
Labels: area/docs, area/security

#1384 Update revision fmts to match RFC-0005
  content/en/flux/cheatsheets/oci-artifacts.md
  content/en/flux/flux-e2e.md
  content/en/flux/get-started.md
  content/en/flux/gitops-toolkit/source-watcher.md
  content/en/flux/guides/helmreleases.md
  content/en/flux/guides/monitoring.md
  content/en/flux/migration/flux-v1-automation-migration.md
  content/en/flux/migration/flux-v1-migration.md
Labels: area/docs

#1374 image-reflector-controller v1beta2 updates
  content/en/flux/cheatsheets/bootstrap.md
  content/en/flux/cheatsheets/oci-artifacts.md
  content/en/flux/gitops-toolkit/packages.md
  content/en/flux/guides/cron-job-image-auth.md
  content/en/flux/guides/image-update.md
  content/en/flux/guides/sortable-image-tags.md
  content/en/flux/migration/flux-v1-automation-migration.md
  hack/import-flux2-assets.sh
Labels: area/docs

#1386 Disable Kubernetes cluster role aggregations at bootstrap
  content/en/flux/cheatsheets/bootstrap.md
Labels: area/docs

#1388 add flagger docs for metric template variables
  content/en/flagger/_index.md
  content/en/flagger/usage/metrics.md
Labels: area/docs, area/flagger

#1387 bugfix patch for notifications fluxcd v0.39.0 tf-controller v0.13.1
  content/en/flux/cheatsheets/bootstrap.md
Labels: area/docs

#1389 Add Flux media types to OCI docs
  content/en/flux/cheatsheets/oci-artifacts.md
Labels: area/docs
