Repository fluxcd/website, pull requests merged in 2023-03, with the labels that each got.

#1391 Add B1 Systems to adopters
  data/adopters/1-flux-v2.yaml
  static/img/logos/b1-systems.png
Labels: area/adopters

#1365 February update
  content/en/blog/2023-03-01-february-update/flux-logo-featured.png
  content/en/blog/2023-03-01-february-update/index.md
  content/en/blog/2023-03-01-february-update/truelayer-post.png
Labels: area/blog

#1385 Trim landing page by merging sections
  assets/scss/_index.scss
  assets/scss/blocks/_blocks.scss
  assets/scss/blocks/_features.scss
  assets/scss/blocks/_hero.scss
  content/en/_index.html
  layouts/shortcodes/blocks/featureitem.html
  layouts/shortcodes/blocks/project.html
  layouts/shortcodes/home/adopters_wall.html
  layouts/shortcodes/home/announce.html
  layouts/shortcodes/home/benefits.html
  layouts/shortcodes/home/calendar.html
  layouts/shortcodes/home/cncf.html
  layouts/shortcodes/home/community.html
  layouts/shortcodes/home/contributors.html
  layouts/shortcodes/home/endorsements.html
  layouts/shortcodes/home/features.html
  layouts/shortcodes/home/next_event.html
  layouts/shortcodes/home/resources_section.html
Labels: landing page

#1394 Calendar: limit session title width, elipsise
  assets/scss/_index.scss
  assets/scss/blocks/_calendar.scss
Labels: ux, landing page

#1395 Add TrueLayer to adopters
  data/adopters/1-flux-v2.yaml
  static/img/logos/truelayer.png
Labels: area/adopters

#1398 Add MyTaxi to adopters
  data/adopters/1-flux-v2.yaml
  static/img/logos/mytaxi.png
Labels: area/adopters

#1399 Add scaleaq to adopters
  data/adopters/1-flux-v2.yaml
  static/img/logos/scaleaq.svg
Labels: area/adopters

#1362 landing page: remove terminal for now
  assets/css/asciinema-player.css
  assets/js/asciinema-player.js
  assets/scss/_terminal.scss
  assets/scss/blocks/_hero.scss
  assets/scss/main.scss
  layouts/partials/asciinema-head.html
  layouts/partials/hooks/head-end.html
  layouts/shortcodes/blocks/hero.html
Labels: help wanted, landing page

#1403 Add Enliven Systems and Szerzi to adopters for Flux v2 as well.
  data/adopters/1-flux-v2.yaml
  data/adopters/3-flux-v1.yaml
  static/img/logos/enliven-systems.png
  static/img/logos/szerzi.png
Labels: area/adopters

#1406 clarify --no-remote-base usage for remote files
  content/en/flux/faq.md
Labels: area/docs

#1410 helm: provide proper option name for drift detection
  content/en/flux/components/helm/options.md
Labels: area/docs

#1416 Add BlakYaks to adopters
  data/adopters/1-flux-v2.yaml
  data/adopters/2-flagger.yaml
  static/img/logos/blakyaks.png
Labels: area/adopters

#1417 bring back 'get started' link and pre-graduation hero text
  content/en/_index.html
Labels: landing page

#1422 docs: document `CorrectDrift` feature gate
  content/en/flux/components/helm/options.md
Labels: area/docs

#1423 Fix cluster role patch
  content/en/flux/cheatsheets/bootstrap.md
Labels: area/docs

#1421 Add documentation for new `--deploy-token-auth` option
  content/en/flux/installation.md
Labels: area/docs

#1424 Add Terraform Provider to GA roadmap
  content/en/roadmap.md
Labels: area/roadmap

#1429 fix note on default key algorithm for bootstrap
  content/en/flux/installation.md
Labels: area/docs
