Repository fluxcd/website, pull requests merged in 2024-01, with the labels that each got.

#1762 Add SOFTSWISS Game Aggregator to adopters
  data/adopters/1-flux-v2.yaml
  static/img/logos/softswiss-game-aggregator.svg
Labels: area/adopters

#1761 Fix spelling error in roadmap.md
  content/en/roadmap.md
Labels: backport:v2-2

#1770 update hugo to v0.121.2
  netlify.toml
Labels: backport:v2-2

#1773 Add Kurator to Flagger adopters
  data/adopters/2-flagger.yaml
  static/img/logos/kurator.svg
Labels: area/adopters, area/flagger

#1790 update hugo to v0.122.0
  netlify.toml
Labels: backport:v2-2

#1793 feat(flux-adopters): add STRG.at GmbH
  data/adopters/1-flux-v2.yaml
  static/img/logos/strg-at.png
Labels: area/adopters, area/flux, backport:v2-2

#1795 Change netlify 6-hourly job to update current release
  .github/workflows/netlify.yml
Labels: backport:v2-2
