Repository fluxcd/website, pull requests merged in 2025-04, with the labels that each got.

#2190 Add privacy policy
  content/en/privacy.md
  hugo.yaml
Labels: backport:v2-5

#2192 chore: add Beekeeper AG as adopter
  data/adopters/1-flux-v2.yaml
  static/img/logos/beekeeper.png
Labels: area/adopters, backport:v2-5

#2189 docs: add a FAQ section to CEL cheatsheet and discuss missing fields
  content/en/flux/cheatsheets/cel-healthchecks.md
Labels: backport:v2-5

#2197 Update roadmap for Flux v2.6
  content/en/roadmap.md
Labels: area/roadmap, backport:v2-5

#2182 Add blog post about GitHub App auth with flux-operator
  content/en/blog/2025-04-14-flux-operator-github-app-bootstrap/featured-image.png
  content/en/blog/2025-04-14-flux-operator-github-app-bootstrap/index.md
Labels: area/blog, backport:v2-5

#2201 docs(kustomize-controller): update feature-gates
  content/en/flux/components/kustomize/options.md
Labels: backport:v2-5

#2204 Add github app docs to flux-operator blog post
  content/en/blog/2025-04-14-flux-operator-github-app-bootstrap/index.md
Labels: backport:v2-5

#2208 Fix podinfo OCI version in docs
  content/en/flux/cheatsheets/oci-artifacts.md
  content/en/flux/guides/helmreleases.md
Labels: area/docs, backport:v2-5
