Repository fluxcd/website, pull requests merged in 2025-02, with the labels that each got.

#2138 Update roadmap
  content/en/roadmap.md
Labels: backport:v2-4

#2140 Conclude roadmap for 2.5
  content/en/roadmap.md
Labels: backport:v2-4

#2142 add docs for GroupChangeLog feature gate
  content/en/flux/components/kustomize/options.md
Labels: area/flux

#2150 Update website banner to 2.5
  content/en/_index.html
Labels: backport:v2-5

#2154 chore: add cephcluster and clustersecretstore examples
  content/en/flux/cheatsheets/cel-healthchecks.md
Labels: backport:v2-5

#2156 Add a note on Forgejo support
  content/en/flux/installation/bootstrap/gitea.md
Labels: area/docs, area/flux, backport:v2-5

#2158 Fix link to health checks library
  content/en/blog/2025-02-20-announcing-flux-v2.5.0/index.md
Labels: backport:v2-5

#2161 Update the GitHub Actions Auto Pull Request use case
  content/en/flux/use-cases/gh-actions-auto-pr.md
Labels: backport:v2-5
