Repository fluxcd/website, pull requests merged in 2025-01, with the labels that each got.

#2112 Roadmap: Add milestones for 2025
  content/en/roadmap.md
Labels: area/roadmap, backport:v2-4

#2118 update Resources block on main page
  assets/scss/_index.scss
Labels: backport:v2-4

#2121 Fix duplicate entry in adopters list
  data/adopters/1-flux-v2.yaml
Labels: backport:v2-4

#2124 add Kong as an adopter
  data/adopters/1-flux-v2.yaml
  static/img/logos/kong.png
Labels: area/adopters, backport:v2-4

#2126 Update alerting integrations for Flux 2.5 roadmap
  content/en/roadmap.md
Labels: area/roadmap, backport:v2-4

#2128 Add subsection for Git providers supporting commit status updates
  content/en/flux/cheatsheets/oci-artifacts.md
Labels: area/docs, area/flux

#2129 Update roadmap with OCI origin revision done
  content/en/roadmap.md
Labels: backport:v2-4

#2130 Mark source controller's Github App Auth implementation as done in rroadmap
  content/en/roadmap.md
Labels: backport:v2-4

#2133 Fix RFC 0009 pull request link on roadmap
  content/en/roadmap.md
Labels: backport:v2-4
